Outputs:
  CitrixADCIAMRole:
    Description: Citrix ADC IAM Role
    Export:
      Name: !Sub '${AWS::StackName}-CitrixADCIAMRole'
    Value: !Sub 'https://console.aws.amazon.com/iam/home#/roles/${CitrixADCIAMRole}'
  CitrixADCInstanceProfile:
    Description: Citrix ADC IAM Instance Profile
    Export:
      Name: !Sub '${AWS::StackName}-CitrixADCInstanceProfile'
    Value: !Ref 'CitrixADCInstanceProfile'
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CitrixADCIAMRole:
    Properties:
      Path: /
      Description: Citrix ADC IAM Role
      Policies:
        - PolicyName: Citrixadc-instance-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ec2:DescribeInstances
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DetachNetworkInterface
                  - ec2:AttachNetworkInterface
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - ec2:RebootInstances
                  - ec2:DescribeAddresses
                  - ec2:AssociateAddress
                  - ec2:DisassociateAddress
                  - sns:CreateTopic
                  - sns:DeleteTopic
                  - sns:ListTopics
                  - sns:Subscribe
                  - sqs:CreateQueue
                  - sqs:ListQueues
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:SetQueueAttributes
                  - iam:SimulatePrincipalPolicy
                  - iam:GetRole
                  - ec2:UnassignPrivateIpAddresses
                  - ec2:AssignPrivateIpAddresses
                Resource: '*'
                Effect: Allow
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub ec2.${AWS::URLSuffix}
    Type: AWS::IAM::Role
  CitrixADCInstanceProfile:
    Properties:
      Path: /
      Roles:
        - !Ref 'CitrixADCIAMRole'
    Type: AWS::IAM::InstanceProfile
