Conditions:
  AssignClientEIP: !Equals
    - !Ref 'ClientENIEIP'
    - 'Yes'
Outputs:
  LambdaConfigureHASameAZRole:
    Description: ''
    Export:
      Name: !Sub '${AWS::StackName}-LambdaConfigureHASameAZRole'
    Value: !Sub 'https://console.aws.amazon.com/iam/home#/roles/${LambdaConfigureHASameAZRole}'
  ClientEIP:
    Description: Client VIP Public IP
    Export:
      Name: !Sub '${AWS::StackName}-ClientEIP'
    Value: !GetAtt 'ConfigureLambda.client_eip'
    Condition: AssignClientEIP
  FloatingVIP:
    Description: floating VIP which migrates between primary and secondary ADCs upon
      failover
    Export:
      Name: !Sub '${AWS::StackName}-FloatingVIP'
    Value: !GetAtt 'ConfigureLambda.floating_vip'
  FloatingSNIP:
    Description: floating SNIP which migrates between primary and secondary ADCs upon
      failover
    Export:
      Name: !Sub '${AWS::StackName}-FloatingSNIP'
    Value: !GetAtt 'ConfigureLambda.floating_snip'
Parameters:
  ADCCustomPassword:
    Type: String
    AllowedPattern: '[.\S]{8,15}'
    ConstraintDescription: Password length must be minimum 8 and maximum 15 characters.
      Whitespace characters not allowed.
    Description: Strong password recommended. Password length must be minimum 8 and
      maximum 15 characters. Whitespace characters not allowed.
    NoEcho: true
  PrimaryInstanceID:
    Type: String
    Description: ''
  PrimaryManagementPrivateIP:
    Type: String
    Default: ''
    Description: ''
    AllowedPattern: ()|(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
    ConstraintDescription: Must be a valid IP of the form x.x.x.x
  ManagementPrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: ''
  ManagementSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ''
  SecondaryInstanceID:
    Type: String
    Description: ''
  SecondaryManagementPrivateIP:
    Type: String
    Default: ''
    Description: ''
    AllowedPattern: ()|(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
    ConstraintDescription: Must be a valid IP of the form x.x.x.x
  ClientENIEIP:
    Type: String
    Description: ''
    Default: 'Yes'
    AllowedValues:
      - 'No'
      - 'Yes'
  S3BucketName:
    Type: String
    Description: ''
    AllowedPattern: ()|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
  S3Key:
    Type: String
    Description: ''
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaConfigureHASameAZRole:
    Properties:
      Description: ''
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: citrixadc-lambda-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ec2:DescribeInstances
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcs
                  - ec2:DescribeAvailabilityZones
                  - ec2:DescribeInstanceStatus
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:AttachNetworkInterface
                  - ec2:DetachNetworkInterface
                  - ec2:ModifyNetworkInterfaceAttribute
                  - ec2:ResetNetworkInterfaceAttribute
                  - ec2:AssignPrivateIpAddresses
                  - ec2:UnassignPrivateIpAddresses
                  - ec2:AllocateAddress
                  - ec2:ReleaseAddress
                  - ec2:AssociateAddress
                  - ec2:DisassociateAddress
                Resource: '*'
                Effect: Allow
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub lambda.${AWS::URLSuffix}
    Type: AWS::IAM::Role
  ConfigureHASameAZFunction:
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ConfigureHASameAZFunction'
      Code:
        S3Bucket: !Ref 'S3BucketName'
        S3Key: !Ref 'S3Key'
      Description: ConfigureHASameAZFunction
      Handler: lambda_ha_same_az.lambda_handler
      Role: !GetAtt 'LambdaConfigureHASameAZRole.Arn'
      Runtime: python3.9
      Timeout: 900
      VpcConfig:
        SecurityGroupIds:
          - !Ref 'ManagementSecurityGroupID'
        SubnetIds:
          - !Ref 'ManagementPrivateSubnetID'
    Type: AWS::Lambda::Function
  ConfigureLambda:
    Properties:
      ServiceToken: !GetAtt 'ConfigureHASameAZFunction.Arn'
      CustomADCPassword: !Ref 'ADCCustomPassword'
      PrimaryADCInstanceID: !Ref 'PrimaryInstanceID'
      PrimaryADCPrivateNSIP: !Ref 'PrimaryManagementPrivateIP'
      SecondaryADCInstanceID: !Ref 'SecondaryInstanceID'
      SecondaryADCPrivateNSIP: !Ref 'SecondaryManagementPrivateIP'
      ClientENIEIP: !Ref 'ClientENIEIP'
    Type: AWS::CloudFormation::CustomResource
