Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      ManagementPrivateSubnetID:
        default: Subnet ID associated with Citrix ADC Management interface
      ClientPublicSubnetID:
        default: Subnet ID associated with Citrix ADC Client interface
      ServerPrivateSubnetID:
        default: Subnet ID associated with Citrix ADC Client interface
      VPCTenancy:
        default: ''
      CitrixADCInstanceType:
        default: Citrix ADC instance type
      KeyPairName:
        default: Keypair to associate to ADCs
      PublishCloudwatchMetrics:
        default: Publish custom metrics to CloudWatch?
      CitrixADCInstanceProfile:
        default: IAM Instance Profile ARN associatd with Citrix ADC
      ManagementSecurityGroupID:
        default: Management Security Group ID
      ClientSecurityGroupID:
        default: Client Security Group ID
      ServerSecurityGroupID:
        default: Server Security Group ID
      CitrixADCImageID:
        default: Citrix ADC AMI ID
      ClientENIEIP:
        default: Should PublicIP(EIP) be assigned to client interfaces?
      ManagementENIEIP:
        default: Should PublicIP(EIP) be assigned to management interfaces?
      ADCInstanceTagName:
        default: ADC Instance Tag Name
      ManagementPrivateIP:
        default: Management Private IP (NSIP)
      ClientPrivateIP:
        default: Client Private IP (VIP)
      ServerPrivateIP:
        default: Server Private IP (SNIP)
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - ManagementPrivateSubnetID
          - ClientPublicSubnetID
          - ServerPrivateSubnetID
          - VPCTenancy
      - Label:
          default: Citrix ADC Configuration
        Parameters:
          - CitrixADCInstanceType
          - KeyPairName
          - PublishCloudwatchMetrics
          - CitrixADCInstanceProfile
          - ManagementSecurityGroupID
          - ClientSecurityGroupID
          - ServerSecurityGroupID
      - Label:
          default: Optional Configuration
        Parameters:
          - CitrixADCImageID
          - ClientENIEIP
          - ManagementENIEIP
          - ADCInstanceTagName
          - ManagementPrivateIP
          - ClientPrivateIP
          - ServerPrivateIP
Conditions:
  AssignEIP2ManagementENI: !Equals
    - !Ref 'ManagementENIEIP'
    - 'Yes'
  AssignEIP2ClientENI: !Equals
    - !Ref 'ClientENIEIP'
    - 'Yes'
  UseManagementPrivateIP: !Not
    - !Equals
      - !Ref 'ManagementPrivateIP'
      - ''
  UseClientPrivateIP: !Not
    - !Equals
      - !Ref 'ClientPrivateIP'
      - ''
  UseServerPrivateIP: !Not
    - !Equals
      - !Ref 'ServerPrivateIP'
      - ''
  IsEncryptedRootVolume: !Equals
    - !Ref EncryptedRootVolume
    - 'true'
Outputs:
  ManagementPrivateIP:
    Description: ADC Management Private IP (NSIP)
    Export:
      Name: !Sub '${AWS::StackName}-ManagementPrivateIP'
    Value: !GetAtt 'ManagementENI.PrimaryPrivateIpAddress'
  ClientPrivateIP:
    Description: ADC Client Private IP (VIP)
    Export:
      Name: !Sub '${AWS::StackName}-ClientPrivateIP'
    Value: !GetAtt 'ClientENI.PrimaryPrivateIpAddress'
  ServerPrivateIP:
    Description: ADC Server Private IP (SNIP)
    Export:
      Name: !Sub '${AWS::StackName}-ServerPrivateIP'
    Value: !GetAtt 'ServerENI.PrimaryPrivateIpAddress'
  CitrixADCInstanceID:
    Description: Citrix ADC Instance ID
    Export:
      Name: !Sub '${AWS::StackName}-CitrixADCInstanceID'
    Value: !Ref 'CitrixADCInstance'
  ManagementEIP:
    Description: ''
    Export:
      Name: !Sub '${AWS::StackName}-ManagementEIP'
    Value: !Ref 'ManagementEIP'
    Condition: AssignEIP2ManagementENI
  ClientEIP:
    Description: ''
    Export:
      Name: !Sub '${AWS::StackName}-ClientEIP'
    Value: !Ref 'ClientEIP'
    Condition: AssignEIP2ClientENI
Parameters:
  CitrixADCImageID:
    Type: String
    Description: ''
  ManagementPrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: ''
  ClientPublicSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: ''
  ServerPrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: ''
  ManagementPrivateIP:
    Type: String
    Default: ''
    Description: If not specified, the private ip will be auto assigned
    AllowedPattern: ()|(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
    ConstraintDescription: Must be a valid IP of the form x.x.x.x
  ClientPrivateIP:
    Type: String
    Default: ''
    Description: If not specified, the private ip will be auto assigned
    AllowedPattern: ()|(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
    ConstraintDescription: Must be a valid IP of the form x.x.x.x
  ServerPrivateIP:
    Type: String
    Default: ''
    Description: If not specified, the private ip will be auto assigned
    AllowedPattern: ()|(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
    ConstraintDescription: Must be a valid IP of the form x.x.x.x
  ClientENIEIP:
    Type: String
    Description: ''
    Default: 'No'
    AllowedValues:
      - 'No'
      - 'Yes'
  ManagementENIEIP:
    Type: String
    Description: ''
    Default: 'No'
    AllowedValues:
      - 'No'
      - 'Yes'
  ADCInstanceTagName:
    Type: String
    Description: ''
  KeyPairName:
    Type: String
    Description: ''
    Default: ''
  VPCTenancy:
    Type: String
    Description: ''
    Default: default
    AllowedValues:
      - default
      - dedicated
  CitrixADCInstanceType:
    Type: String
    Description: ''
    Default: m5.xlarge
    AllowedValues:
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m4.16xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.12xlarge
      - c5.18xlarge
      - c5.24xlarge
      - c5n.large
      - c5n.xlarge
      - c5n.2xlarge
      - c5n.4xlarge
      - c5n.9xlarge
      - c5n.18xlarge
  CitrixADCInstanceProfile:
    Type: String
    Description: ''
    Default: ''
  ManagementSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ''
  ClientSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ''
  ServerSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ''
  PublishCloudwatchMetrics:
    Type: String
    Description: ''
    Default: 'Yes'
    AllowedValues:
      - 'No'
      - 'Yes'
  EncryptedRootVolume:
    Description: Should the root volume be encrypted? (true/false)
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be 'true' or 'false'.
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ManagementENI:
    Properties:
      Description: ADC Management Private IP (NSIP)
      GroupSet:
        - !Ref 'ManagementSecurityGroupID'
      PrivateIpAddress: !If
        - UseManagementPrivateIP
        - !Ref 'ManagementPrivateIP'
        - !Ref 'AWS::NoValue'
      SubnetId: !Ref 'ManagementPrivateSubnetID'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ManagementENI'
    Type: AWS::EC2::NetworkInterface
  ClientENI:
    Properties:
      Description: ADC Client Private IP (VIP)
      GroupSet:
        - !Ref 'ClientSecurityGroupID'
      PrivateIpAddress: !If
        - UseClientPrivateIP
        - !Ref 'ClientPrivateIP'
        - !Ref 'AWS::NoValue'
      SubnetId: !Ref 'ClientPublicSubnetID'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ClientENI'
    Type: AWS::EC2::NetworkInterface
  ServerENI:
    Properties:
      Description: ADC Server Private IP (SNIP)
      GroupSet:
        - !Ref 'ServerSecurityGroupID'
      PrivateIpAddress: !If
        - UseServerPrivateIP
        - !Ref 'ServerPrivateIP'
        - !Ref 'AWS::NoValue'
      SubnetId: !Ref 'ServerPrivateSubnetID'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ServerENI'
    Type: AWS::EC2::NetworkInterface
  CitrixADCInstance:
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-${ADCInstanceTagName}-CitrixADCInstance'
      IamInstanceProfile: !Ref 'CitrixADCInstanceProfile'
      ImageId: !Ref 'CitrixADCImageID'
      InstanceType: !Ref 'CitrixADCInstanceType'
      KeyName: !Ref 'KeyPairName'
      NetworkInterfaces:
        - DeviceIndex: '0'
          NetworkInterfaceId: !Ref 'ManagementENI'
        - DeviceIndex: '1'
          NetworkInterfaceId: !Ref 'ClientENI'
        - DeviceIndex: '2'
          NetworkInterfaceId: !Ref 'ServerENI'
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            Encrypted: !If
              - IsEncryptedRootVolume
              - true
              - false
      Tenancy: !Ref 'VPCTenancy'
      UserData: !Base64
        Fn::Sub: PublishCloudwatchMetrics=${PublishCloudwatchMetrics}
    Type: AWS::EC2::Instance
  ManagementEIP:
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ManagementEIP'
    Type: AWS::EC2::EIP
    Condition: AssignEIP2ManagementENI
    DependsOn: CitrixADCInstance
  AssociateManagementEIP2ENI:
    Properties:
      AllocationId: !GetAtt 'ManagementEIP.AllocationId'
      NetworkInterfaceId: !Ref 'ManagementENI'
      PrivateIpAddress: !GetAtt 'ManagementENI.PrimaryPrivateIpAddress'
    Type: AWS::EC2::EIPAssociation
    Condition: AssignEIP2ManagementENI
  ClientEIP:
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ClientEIP'
    Type: AWS::EC2::EIP
    Condition: AssignEIP2ClientENI
    DependsOn: CitrixADCInstance
  AssociateClientEIP2ENI:
    Properties:
      AllocationId: !GetAtt 'ClientEIP.AllocationId'
      NetworkInterfaceId: !Ref 'ClientENI'
      PrivateIpAddress: !GetAtt 'ClientENI.PrimaryPrivateIpAddress'
    Type: AWS::EC2::EIPAssociation
    Condition: AssignEIP2ClientENI
