Outputs:
  PooledLicenseRole:
    Description: ''
    Export:
      Name: !Sub '${AWS::StackName}-PooledLicenseRole'
    Value: !Sub 'https://console.aws.amazon.com/iam/home#/roles/${PooledLicenseRole}'
Parameters:
  ADCInstanceID:
    Type: String
    Description: ''
  ADCCustomPassword:
    Type: String
    AllowedPattern: '[.\S]{8,15}'
    ConstraintDescription: Password length must be minimum 8 and maximum 15 characters.
      Whitespace characters not allowed.
    Description: Strong password recommended. Password length must be minimum 8 and
      maximum 15 characters. Whitespace characters not allowed.
    NoEcho: true
  ManagementPrivateIP:
    Type: String
    Default: ''
    Description: ''
    AllowedPattern: ()|(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
    ConstraintDescription: Must be a valid IP of the form x.x.x.x
  ManagementSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ''
  ManagementPrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: ''
  LicensingMode:
    Type: String
    Description: ''
    AllowedValues:
      - ''
      - Pooled-Licensing
      - CICO-Licensing
      - CPU-Licensing
    Default: ''
  ADMIP:
    Type: String
    Default: ''
    Description: ''
    AllowedPattern: ()|(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
    ConstraintDescription: Must be a valid IP of the form x.x.x.x
  Bandwidth:
    Type: Number
    Description: 'Should be multile of 10 Mbps. Initial bandwidth of the license in
      Mbps to be allocated after BYOL ADC is created. '
  PooledEdition:
    Type: String
    Description: ''
    AllowedValues:
      - ''
      - Standard
      - Advanced
      - Premium
    Default: ''
  Platform:
    Type: String
    Description: ''
    AllowedValues:
      - ''
      - VPX-10
      - VPX-25
      - VPX-200
      - VPX-1000
      - VPX-3000
      - VPX-5000
      - VPX-8000
      - VPX-10G
      - VPX-15G
      - VPX-25G
      - VPX-40G
      - VPX-100G
    Default: ''
  VCPUEdition:
    Type: String
    Description: ''
    AllowedValues:
      - ''
      - Standard
      - Advanced
      - Premium
    Default: ''
  S3BucketName:
    Type: String
    Description: ''
    AllowedPattern: ()|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
  S3Key:
    Type: String
    Description: ''
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PooledLicenseRole:
    Properties:
      Description: ''
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: citrixadc-lambda-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ec2:DescribeInstances
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcs
                  - ec2:DescribeAvailabilityZones
                  - ec2:DescribeInstanceStatus
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:AttachNetworkInterface
                  - ec2:DetachNetworkInterface
                  - ec2:ModifyNetworkInterfaceAttribute
                  - ec2:ResetNetworkInterfaceAttribute
                  - ec2:AssignPrivateIpAddresses
                  - ec2:UnassignPrivateIpAddresses
                  - ec2:AllocateAddress
                  - ec2:ReleaseAddress
                  - ec2:AssociateAddress
                  - ec2:DisassociateAddress
                Resource: '*'
                Effect: Allow
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub lambda.${AWS::URLSuffix}
    Type: AWS::IAM::Role
  PooledLicenseFunction:
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-PooledLicenseFunction'
      Code:
        S3Bucket: !Ref 'S3BucketName'
        S3Key: !Ref 'S3Key'
      Description: PooledLicenseFunction
      Handler: lambda_pooled_license.lambda_handler
      Role: !GetAtt 'PooledLicenseRole.Arn'
      Runtime: python3.6
      Timeout: 900
      VpcConfig:
        SecurityGroupIds:
          - !Ref 'ManagementSecurityGroupID'
        SubnetIds:
          - !Ref 'ManagementPrivateSubnetID'
    Type: AWS::Lambda::Function
  AllocatePooledLicense:
    Properties:
      ServiceToken: !GetAtt 'PooledLicenseFunction.Arn'
      CustomADCPassword: !Ref 'ADCCustomPassword'
      ADCInstanceID: !Ref 'ADCInstanceID'
      ADCPrivateNSIP: !Ref 'ManagementPrivateIP'
      ADMIP: !Ref 'ADMIP'
      LicensingMode: !Ref 'LicensingMode'
      Bandwidth: !Ref 'Bandwidth'
      PooledEdition: !Ref 'PooledEdition'
      Platform: !Ref 'Platform'
      VCPUEdition: !Ref 'VCPUEdition'
    Type: AWS::CloudFormation::CustomResource
