Outputs:
  LatestAMILambdaRole:
    Description: ''
    Export:
      Name: !Sub '${AWS::StackName}-LatestAMILambdaRole'
    Value: !Sub 'https://console.aws.amazon.com/iam/home#/roles/${LatestAMILambdaRole}'
  LatestAMI:
    Description: Latest AMI
    Export:
      Name: !Sub '${AWS::StackName}-LatestAMI'
    Value: !GetAtt 'AMIInfo.LatestADCAMI'
Parameters:
  ADCProductName:
    Type: String
    Description: ''
    Default: Citrix ADC VPX - Customer Licensed
    AllowedValues:
      - Citrix ADC VPX - Customer Licensed
  ADCProductVersion:
    Type: String
    Description: ''
    Default: '14.1'
    AllowedValues:
      - '13.0'
      - '13.1'
      - '14.1'
  S3BucketName:
    Type: String
    Description: ''
    AllowedPattern: ()|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
  S3Key:
    Type: String
    Description: ''
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LatestAMILambdaRole:
    Properties:
      Path: /
      Description: ''
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub lambda.${AWS::URLSuffix}
      Policies:
        - PolicyName: GetVPCCIDR
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ec2:DescribeImages
                Resource: '*'
                Effect: Allow
    Type: AWS::IAM::Role
  AMIInfoFunction:
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-AMIInfoFunction'
      Code:
        S3Bucket: !Ref 'S3BucketName'
        S3Key: !Ref 'S3Key'
      Description: AMIInfoFunction
      Handler: lambda_get_latest_citrixadc_ami.lambda_handler
      Role: !GetAtt 'LatestAMILambdaRole.Arn'
      Runtime: python3.9
      Timeout: 30
    Type: AWS::Lambda::Function
  AMIInfo:
    Properties:
      ServiceToken: !GetAtt 'AMIInfoFunction.Arn'
      ADCProduct: !Ref 'ADCProductName'
      ADCVersion: !Ref 'ADCProductVersion'
    Type: AWS::CloudFormation::CustomResource
