Description: This template provisions a Citrix ADC VPX in AWS. This template also
  gives an option to allocate Pooled License to Citrix ADCs while provisioning.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      VPCID:
        default: VPC ID to deploy the resources
      RestrictedWebAppCIDR:
        default: Address range to access apps behind the ADCs
      RestrictedSSHCIDR:
        default: Address range to access Management interfaces
      SubnetID:
        default: Subnet ID associated with  ADC Management interface
      VPCTenancy:
        default: ''
      ADCProductName:
        default: Citrix ADC Product Name
      ADCProductVersion:
        default: Citrix ADC Product Version
      ADCCustomPassword:
        default: Citrix ADC management login Password
      CitrixADCInstanceType:
        default: Citrix ADC instance type
      RPCNodePassword:
        default: Citrix ADC RPC Node Password
      KeyPairName:
        default: Keypair to associate to ADCs
      PublishCloudwatchMetrics:
        default: Publish custom metrics to CloudWatch?
      CitrixADCImageID:
        default: Citrix ADC AMI ID
      ManagementENIEIP:
        default: Should PublicIP(EIP) be assigned to management interfaces?
      S3BucketName:
        default: S3 bucket name
      PooledLicense:
        default: Do you want to allocate license from ADM?
      ADMIP:
        default: Reachable ADM or ADM Agent IP
      LicensingMode:
        default: Licensing Mode
      Bandwidth:
        default: Pooled-Licensing Bandwidth in Mbps (Select this if the above LicensingMode
          is `Pooled-Licensing`)
      PooledEdition:
        default: Pooled-Licensing License Edition (Select this if the above LicensingMode
          is `Pooled-Licensing`)
      Platform:
        default: CICO-Licensing Appliance Platform Type (Select this if the above
          LicensingMode is `CICO-Licensing`)
      VCPUEdition:
        default: CPU-Licensing Edition (Select this if the above LicensingMode is
          `CPU-Licensing`)
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VPCID
          - RestrictedWebAppCIDR
          - RestrictedSSHCIDR
          - SubnetID
          - VPCTenancy
      - Label:
          default: Citrix ADC Configuration
        Parameters:
          - ADCProductName
          - ADCProductVersion
          - ADCCustomPassword
          - RPCNodePassword
          - CitrixADCInstanceType
          - KeyPairName
          - PublishCloudwatchMetrics
      - Label:
          default: Optional Configuration
        Parameters:
          - CitrixADCImageID
          - ManagementENIEIP
          - S3BucketName
      - Label:
          default: License Server Configuration (Optional)
        Parameters:
          - PooledLicense
          - ADMIP
          - LicensingMode
          - Bandwidth
          - PooledEdition
          - Platform
          - VCPUEdition
Conditions:
  RPCNodePasswordSameAsADCCustomPassword: !Equals [!Ref RPCNodePassword, ""]
  UseLatestAMI: !Equals
    - !Ref 'CitrixADCImageID'
    - ''
  AssignEIP2ManagementENI: !Equals
    - !Ref 'ManagementENIEIP'
    - 'Yes'
  UsePooledLicense: !Equals
    - !Ref 'PooledLicense'
    - 'Yes'
Outputs:
  CitrixADCIP:
    Description: ' Citrix ADC Public Management IP'
    Export:
      Name: !Sub '${AWS::StackName}-CitrixADCIP'
    Value: !GetAtt 'CitrixADCStack.Outputs.ManagementEIP'
    Condition: AssignEIP2ManagementENI
  CitrixADCInstanceID:
    Description: ' Citrix ADC Instance ID'
    Export:
      Name: !Sub '${AWS::StackName}-CitrixADCInstanceID'
    Value: !GetAtt 'CitrixADCStack.Outputs.CitrixADCInstanceID'
  ManagementSecurityGroupID:
    Description: Security Group associated with Management Interfaces
    Export:
      Name: !Sub '${AWS::StackName}-ManagementSecurityGroupID'
    Value: !GetAtt 'SecurityGroupStack.Outputs.ManagementSG'
  ClientSecurityGroupID:
    Description: Security Group associated with Client Interfaces
    Export:
      Name: !Sub '${AWS::StackName}-ClientSecurityGroupID'
    Value: !GetAtt 'SecurityGroupStack.Outputs.ClientSG'
  ServerSecurityGroupID:
    Description: Security Group associated with Server Interfaces
    Export:
      Name: !Sub '${AWS::StackName}-ServerSecurityGroupID'
    Value: !GetAtt 'SecurityGroupStack.Outputs.ServerSG'
Parameters:
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: ''
  RestrictedWebAppCIDR:
    Type: String
    Description: Must be a valid IP CIDR range of the form x.x.x.x/x
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
  RestrictedSSHCIDR:
    Type: String
    Description: Must be a valid IP CIDR range of the form x.x.x.x/x
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: ''
  VPCTenancy:
    Type: String
    Description: ''
    Default: default
    AllowedValues:
      - default
      - dedicated
  CitrixADCImageID:
    Type: String
    Description: If left empty, the latest AMI for the above selected Citrix ADC Product
      Name and Version will be provisioned.
  ADCProductName:
    Type: String
    Description: ''
    Default: Citrix ADC VPX - Customer Licensed
    AllowedValues:
      - Citrix ADC VPX - Customer Licensed
      - Citrix ADC VPX Express - 20 Mbps
      - Citrix ADC VPX Standard Edition - 10 Mbps
      - Citrix ADC VPX Standard Edition - 200 Mbps
      - Citrix ADC VPX Standard Edition - 1000 Mbps
      - Citrix ADC VPX Standard Edition - 3Gbps
      - Citrix ADC VPX Standard Edition - 5Gbps
      - Citrix ADC VPX Premium Edition - 10 Mbps
      - Citrix ADC VPX Premium Edition - 200 Mbps
      - Citrix ADC VPX Premium Edition - 1000 Mbps
      - Citrix ADC VPX Premium Edition - 3Gbps
      - Citrix ADC VPX Premium Edition - 5Gbps
      - Citrix ADC VPX Advanced Edition - 10 Mbps
      - Citrix ADC VPX Advanced Edition - 200 Mbps
      - Citrix ADC VPX Advanced Edition - 1000 Mbps
      - Citrix ADC VPX Advanced Edition - 3Gbps
      - Citrix ADC VPX Advanced Edition - 5Gbps
  ADCProductVersion:
    Type: String
    Description: ''
    Default: '14.1'
    AllowedValues:
      - '13.0'
      - '13.1'
      - '14.1'
  CitrixADCInstanceType:
    Type: String
    Description: ''
    Default: m5.xlarge
    AllowedValues:
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m4.16xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.12xlarge
      - c5.18xlarge
      - c5.24xlarge
      - c5n.large
      - c5n.xlarge
      - c5n.2xlarge
      - c5n.4xlarge
      - c5n.9xlarge
      - c5n.18xlarge
  ADCCustomPassword:
    Type: String
    AllowedPattern: '[.\S]{8,15}'
    ConstraintDescription: Password length must be minimum 8 and maximum 15 characters.
      Whitespace characters not allowed.
    Description: Strong password recommended. Password length must be minimum 8 and
      maximum 15 characters. Whitespace characters not allowed.
    NoEcho: true
  RPCNodePassword:
    Type: String
    Default: ""
    Description:
      Leave it empty if you want to keep the RPCNodePassword same as the
      ADCCustomPassword. For more details on RPC Node passoword, refer
      https://docs.netscaler.com/en-us/citrix-adc/current-release/getting-started-with-citrix-adc/change-rpc-node-password.html
    NoEcho: true
  KeyPairName:
    Description: ''
    Type: AWS::EC2::KeyPair::KeyName
  ManagementENIEIP:
    Type: String
    Description: ''
    Default: 'No'
    AllowedValues:
      - 'No'
      - 'Yes'
  PublishCloudwatchMetrics:
    Type: String
    Description: ''
    Default: 'Yes'
    AllowedValues:
      - 'No'
      - 'Yes'
  S3BucketName:
    Type: String
    Description: Leave as it is, if unsure
    Default: citrixadc-automation
  PooledLicense:
    Type: String
    Description: ''
    Default: 'No'
    AllowedValues:
      - 'No'
      - 'Yes'
  LicensingMode:
    Type: String
    Description: ''
    AllowedValues:
      - ''
      - Pooled-Licensing
      - CICO-Licensing
      - CPU-Licensing
    Default: ''
  ADMIP:
    Type: String
    Default: ''
    Description: ''
    AllowedPattern: ()|(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
    ConstraintDescription: Must be a valid IP of the form x.x.x.x
  Bandwidth:
    Type: Number
    Description: 'Should be multile of 10 Mbps. Initial bandwidth of the license in
      Mbps to be allocated after BYOL ADC is created. '
    Default: 0
  PooledEdition:
    Type: String
    Description: ''
    AllowedValues:
      - ''
      - Standard
      - Advanced
      - Premium
    Default: ''
  Platform:
    Type: String
    Description: ''
    AllowedValues:
      - ''
      - VPX-10
      - VPX-25
      - VPX-200
      - VPX-1000
      - VPX-3000
      - VPX-5000
      - VPX-8000
      - VPX-10G
      - VPX-15G
      - VPX-25G
      - VPX-40G
      - VPX-100G
    Default: ''
  VCPUEdition:
    Type: String
    Description: ''
    AllowedValues:
      - ''
      - Standard
      - Advanced
      - Premium
    Default: ''
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaCopierStack:
    Properties:
      Parameters:
        S3BucketName: !Sub '${S3BucketName}'
        S3Key: lambda-citrixadc-awscft.zip
      TemplateURL: !Sub 'https://${S3BucketName}.s3.${AWS::URLSuffix}/templates/nested-stacks/cft-stack-lambda-copier.yaml'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-LambdaCopierStack'
    Type: AWS::CloudFormation::Stack
  LatestAMIStack:
    Properties:
      Parameters:
        ADCProductName: !Ref 'ADCProductName'
        ADCProductVersion: !Ref 'ADCProductVersion'
        S3BucketName: !GetAtt 'LambdaCopierStack.Outputs.LambdaZipsBucket'
        S3Key: lambda-citrixadc-awscft.zip
      TemplateURL: !Sub 'https://${S3BucketName}.s3.${AWS::URLSuffix}/templates/nested-stacks/cft-stack-find-latest-ami.yaml'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-LatestAMIStack'
    Type: AWS::CloudFormation::Stack
    Condition: UseLatestAMI
  IAMRoleStack:
    Properties:
      Parameters: {}
      TemplateURL: !Sub 'https://${S3BucketName}.s3.${AWS::URLSuffix}/templates/nested-stacks/cft-stack-citrixadc-iam-role.yaml'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-IAMRoleStack'
    Type: AWS::CloudFormation::Stack
  SecurityGroupStack:
    Properties:
      Parameters:
        RestrictedSSHCIDR: !Ref 'RestrictedSSHCIDR'
        RestrictedWebAppCIDR: !Ref 'RestrictedWebAppCIDR'
        VPCID: !Ref 'VPCID'
      TemplateURL: !Sub 'https://${S3BucketName}.s3.${AWS::URLSuffix}/templates/nested-stacks/cft-stack-securitygroup.yaml'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-SecurityGroupStack'
    Type: AWS::CloudFormation::Stack
  CitrixADCStack:
    Properties:
      Parameters:
        ADCInstanceTagName: CitrixADC1nic
        CitrixADCInstanceProfile: !GetAtt 'IAMRoleStack.Outputs.CitrixADCInstanceProfile'
        CitrixADCImageID: !If
          - UseLatestAMI
          - !GetAtt 'LatestAMIStack.Outputs.LatestAMI'
          - !Ref 'CitrixADCImageID'
        CitrixADCInstanceType: !Ref 'CitrixADCInstanceType'
        KeyPairName: !Ref 'KeyPairName'
        ManagementENIEIP: !Ref 'ManagementENIEIP'
        SubnetID: !Ref 'SubnetID'
        ManagementSecurityGroupID: !GetAtt 'SecurityGroupStack.Outputs.ManagementSG'
        PublishCloudwatchMetrics: !Ref 'PublishCloudwatchMetrics'
        VPCTenancy: !Ref 'VPCTenancy'
      TemplateURL: !Sub 'https://${S3BucketName}.s3.${AWS::URLSuffix}/templates/nested-stacks/cft-stack-standalone-1nic-adc.yaml'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-CitrixADCStack'
    Type: AWS::CloudFormation::Stack
  ADC1nicBootstrapStack:
    Properties:
      Parameters:
        ADCCustomPassword: !Ref 'ADCCustomPassword'
        RPCNodePassword: !If
          - RPCNodePasswordSameAsADCCustomPassword
          - !Ref ADCCustomPassword
          - !Ref RPCNodePassword
        ADCInstanceID: !GetAtt 'CitrixADCStack.Outputs.CitrixADCInstanceID'
        ManagementPrivateIP: !GetAtt 'CitrixADCStack.Outputs.ManagementPrivateIP'
        ManagementPrivateSubnetID: !Ref 'SubnetID'
        ManagementSecurityGroupID: !GetAtt 'SecurityGroupStack.Outputs.ManagementSG'
        S3BucketName: !GetAtt 'LambdaCopierStack.Outputs.LambdaZipsBucket'
        S3Key: lambda-citrixadc-awscft.zip
      TemplateURL: !Sub 'https://${S3BucketName}.s3.${AWS::URLSuffix}/templates/nested-stacks/cft-stack-citrixadc-1nic-bootstrap.yaml'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ADC1nicBootstrapStack'
    Type: AWS::CloudFormation::Stack
  PooledLicenseStack:
    Properties:
      Parameters:
        ADCCustomPassword: !Ref 'ADCCustomPassword'
        ADCInstanceID: !GetAtt 'CitrixADCStack.Outputs.CitrixADCInstanceID'
        ManagementPrivateIP: !GetAtt 'CitrixADCStack.Outputs.ManagementPrivateIP'
        ManagementPrivateSubnetID: !Ref 'SubnetID'
        ManagementSecurityGroupID: !GetAtt 'SecurityGroupStack.Outputs.ManagementSG'
        ADMIP: !Ref 'ADMIP'
        Bandwidth: !Ref 'Bandwidth'
        LicensingMode: !Ref 'LicensingMode'
        Platform: !Ref 'Platform'
        PooledEdition: !Ref 'PooledEdition'
        VCPUEdition: !Ref 'VCPUEdition'
        S3BucketName: !GetAtt 'LambdaCopierStack.Outputs.LambdaZipsBucket'
        S3Key: lambda-citrixadc-awscft.zip
      TemplateURL: !Sub 'https://${S3BucketName}.s3.${AWS::URLSuffix}/templates/nested-stacks/cft-stack-pooled-license.yaml'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-PooledLicenseStack'
    Type: AWS::CloudFormation::Stack
    Condition: UsePooledLicense
    DependsOn: ADC1nicBootstrapStack

